title: Ridvan Cetin's Website
description: My Bioinformatics Journey
theme: jekyll-theme-cayman
author: Ridvan Cetin
baseurl: "/CMO_Atf3_Zfp711_Bcl6b" # Set this to the subdirectory of your site
url: "https://ridvan-cetin.github.io" # Do not include the subdirectory here

# Optional configurations
markdown: kramdown
plugins:
  - jekyll-feed
